### ISSUE TITLE
Key Manager/SCIM - SCIM Role Related Functions

### ISSUE THREAD

**Issue by lakwarus** [wso2/carbon-auth#30]
Component - Key Manager/SCIM

SCIM Role Related Functions

**Comment by malinthaprasan** [comment]
Fixed in https://github.com/wso2/carbon-auth/pull/110

Documentation https://docs.google.com/document/d/1msNXeK2BWjzJXbZXjMaQuUQn5RsfFj71UrGSNinV8Zk/edit#
